name: Remove Fly app

on:
  workflow_dispatch:

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps destroy ethandenny-dev --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
